//GUESSING GAME  PROGECT
// Copyright (C) 2020 Michael Opoku-Gyimah

#include<iostream>
#include<string> // to use strings
#include<cstdlib> //To declare a set of general purpose functions info
#include<ctime> // to manipulate time and data info
using namespace std;
void DrawLine(int x, char sign);
void regulations();

int main()
{
    string ParticipantName;
    int BalanceAmount; // store player's balance money
    int BettingMoney;
    int guess; 
    int dice; //store number generated by the computer
    char option;
    srand(time(0)); // To seed the random generator
    DrawLine(100, '_');
    cout << "\n\n\n\t\tGUESSING GAME\n\n\n\n";
    DrawLine(100, '_');
    cout << " Player Name : ";
    getline(cin, ParticipantName);
    cout << " Enter Amount to start game : $";
    cin >> BalanceAmount;
    do { 
         regulations();
         cout << " Your current balance is $ " << BalanceAmount << "\n";
         //obtain participant's betting money
         do {
             cout << ParticipantName << ", Betting Money : $";
             cin >> BettingMoney;
             if(BettingMoney > BalanceAmount)
             cout << " Betting money exceeds your current balance\n" << "\nTry Again\n ";
         }while(BettingMoney > BalanceAmount);
         //Obtain Participant's numbers
         do
         {
             cout << " Guess your lucky number between 1 to 20 : ";
             cin >> guess;
             if(guess <=0 || guess >20)
             cout << " Oops!! The number should be between 1 to 20\n " << "\nTry Again\n";
         }while(guess <= 0 || guess > 20);
         dice = rand()%20 +1; // To hold the randomly generated integer between 1 to 20
         if(dice == guess)
         {
         cout << "\n\nCongrats!! You are a winner of $. " << BettingMoney * 20;
         BalanceAmount = BalanceAmount + BettingMoney*20;
    }
    else
    {
        cout << " Unfortunate!! You lost $ " << BettingMoney <<"\n";
        BalanceAmount = BalanceAmount - BettingMoney;
    }
    cout << "\nThe Winning Number is : " << dice <<"\n";
    cout <<"\n"<<ParticipantName<<", You have $ " << BalanceAmount << "\n";
    if(BalanceAmount == 0)
    {
        cout << " You no money left to start ";
        break;
    }
    cout << "\n\n-->Do you want to start again (y/n)? ";
    cin >> option;
}while(option == 'Y' || option == 'y');
cout << "\n\n\n";
DrawLine(110, '=');
cout << "\n\nWe appreciate you for playing the game. Your current balance is $ " << BalanceAmount << "\n\n";
DrawLine(110,'=');
return 0;
}
void DrawLine(int x, char sign)
{
    for(int i=0; i<x; i++)
    cout << sign;
    cout << "\n" ;
}
void regulations()
{
    cout << "\n\n";
    DrawLine(120, '-');
    cout << "\t\tREGULATIONS OF THE GAMES\n";
    DrawLine(120, '-');
    cout << "\t1. Select any number between 1 to 20\n";
    cout << "\t2. Winning results in 20 times of the amount you bet\n";
    cout << "\t3. Betting on the wrong number results in losing your betting amount\n";
    cout << "\t4. You can donate 10% of your money to charity if you win\n\n";
    DrawLine(120, '-');
}
      